version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  unit-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            - run: chmod +x ./cc-test-reporter
            - run: ./cc-test-reporter before-build
            - run: yarn install
            - run: yarn run test:unit --coverage
            - run: ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
workflows:
    build-and-test:
      jobs:
        - unit-tests
        - cypress/run:
            name: e2e-tests
            executor: cypress/base-12-16-1
            yarn: true
            command: yarn run test:e2e:run