version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  unit-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn run test:unit
workflows:
    build-and-test:
      jobs:
        - unit-tests
        - e2e-tests:
          - cypress/run:
              executor: cypress/base-12-16-1
              yarn: true
              command: yarn run test:e2e:run